name: fractal
adopt-info: fractal
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict
base: core22
architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

layout:
  /usr/share/fractal:
    symlink: $SNAP/usr/share/fractal
    
slots:
  # for GtkApplication registration
  fractal:
    interface: dbus
    bus: session
    name: org.gnome.Fractal

apps:
  fractal:
    extensions: [gnome]
    command: usr/bin/fractal
    common-id: org.gnome.Fractal
    desktop: usr/share/applications/org.gnome.Fractal.desktop
    plugs:
      - home
      - removable-media
      - network
      - network-bind
      - network-status

parts:
  libshumate:
    source: https://gitlab.gnome.org/GNOME/libshumate.git
    source-tag: '1.0.3'
    plugin: meson
    meson-parameters: [ --prefix=/usr, -Dgir=false, -Dvapi=false, -Dgtk_doc=false]
    override-prime: ''

  rustup:
    plugin: nil
    build-packages: [wget]
    build-environment:
      - RUSTUP_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_HOME: $CRAFT_PART_INSTALL/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
    override-pull: |
      wget https://sh.rustup.rs -O $CRAFT_PART_SRC/rustup-init.sh
      chmod +x $CRAFT_PART_SRC/rustup-init.sh
    override-build: |
      $CRAFT_PART_SRC/rustup-init.sh -y --no-modify-path
      mkdir -p $CRAFT_PART_INSTALL/usr/bin
      for i in `ls $RUSTUP_HOME/bin/`; do
        ln -s ../share/rust/bin/$i $CRAFT_PART_INSTALL/usr/bin/$i
      done
    override-prime: |
      echo 'Skip Prime'
  fractal:
    after: [ rustup, libshumate ]
    parse-info: [ usr/share/metainfo/org.gnome.Fractal.metainfo.xml ]
    source: https://gitlab.gnome.org/GNOME/fractal.git
    source-type: git
    source-tag: '5.beta1'
    plugin: meson
    meson-parameters: [--prefix=/usr, -Dprofile=default, -Doptimization=3, -Dbuildtype=release]
    organize:
      snap/fractal/current: .
    build-packages:
      - curl
      - libssl-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libpipewire-0.3-dev
      - libclang-dev
      - xdg-desktop-portal-dev
    build-environment:
      - RUSTUP_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_HOME: $CRAFT_STAGE/usr/share/rust
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
      - PKG_CONFIG_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig:$PKG_CONFIG_PATH
    override-pull: |
      craftctl default
      patch -p1 < $CRAFT_PROJECT_DIR/fractal.patch
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/fractal/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      #done
    prime:
      - -snap/fractal

  deps:
    plugin: nil
    stage-packages:
      - libgstreamer-plugins-bad1.0-0
      - libpipewire-0.3-0
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET/libpipewire-0.3.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libpipewire-0.3.so.0.348.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstadaptivedemux-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstadaptivedemux-1.0.so.0.2003.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstbadaudio-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstbadaudio-1.0.so.0.2003.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstcodecparsers-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstcodecparsers-1.0.so.0.2003.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstcodecs-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstcodecs-1.0.so.0.2003.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstinsertbin-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstinsertbin-1.0.so.0.2003.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstisoff-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstisoff-1.0.so.0.2003.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstmpegts-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstmpegts-1.0.so.0.2003.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstplay-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstplay-1.0.so.0.2003.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstplayer-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstplayer-1.0.so.0.2003.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstsctp-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstsctp-1.0.so.0.2003.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgsttranscoder-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgsturidownloader-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgsturidownloader-1.0.so.0.2003.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstva-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstva-1.0.so.0.2003.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstwayland-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstwayland-1.0.so.0.2003.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstwebrtc-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET/libgstwebrtc-1.0.so.0.2003.0
