name: fractal
adopt-info: fractal
grade: stable 
confinement: strict
base: core24
platforms:
  amd64:
  arm64:
    
slots:
  # for GtkApplication registration
  fractal:
    interface: dbus
    bus: session
    name: org.gnome.Fractal

apps:
  fractal:
    extensions: [gnome]
    command: usr/bin/fractal
    common-id: org.gnome.Fractal
    desktop: usr/share/applications/org.gnome.Fractal.desktop
    plugs:
      - network
      - network-status
      - audio-playback


parts:
  libshumate:
    source: https://gitlab.gnome.org/GNOME/libshumate.git
    source-tag: '1.3.0'
    plugin: meson
    meson-parameters: [ --prefix=/usr, -Dgir=false, -Dvapi=false, -Dgtk_doc=false]
    prime:
      - -usr/include
      - -usr/lib/*/pkgconfig
      - -usr/share

  fractal:
    after: [ libshumate, pipewire ]
    parse-info: [ usr/share/metainfo/org.gnome.Fractal.metainfo.xml ]
    source: https://gitlab.gnome.org/GNOME/fractal.git
    source-type: git
    source-tag: '8'
    plugin: meson
    meson-parameters: [--prefix=/snap/fractal/current/usr, -Dprofile=default, -Doptimization=3, -Dbuildtype=release]
    build-packages:
      - gperf
      - libssl-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libprotobuf-c-dev
      - libclang-dev
      - libspa-0.2-dev
      - rustc-1.80
      - cargo-1.80
      - xdg-desktop-portal-dev
    build-environment:
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
      - PKG_CONFIG_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:$PKG_CONFIG_PATH 
    organize: 
      snap/fractal/current: .
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/fractal/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done

  pipewire:
    source: https://gitlab.freedesktop.org/pipewire/pipewire.git
    source-tag: '0.3.79'
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - --strip
      - -Dalsa=disabled
      - -Dpipewire-alsa=disabled
      - -Djack=disabled
      - -Dpipewire-jack=disabled
      - -Dsession-managers=[]
      - -Dexamples=disabled
      - -Dman=disabled
      - -Dtests=disabled
    prime:
      - -usr/lib/*/pkgconfig
      - -usr/include


  deps:
    plugin: nil
    stage-packages:
      - libgstreamer-plugins-bad1.0-0
      - libprotobuf-c1
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libprotobuf-c.so.1.0.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libprotobuf-c.so.1
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstadaptivedemux-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstadaptivedemux-1.0.so.0.2402.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstbadaudio-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstbadaudio-1.0.so.0.2402.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstcodecparsers-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstcodecparsers-1.0.so.0.2402.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstcodecs-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstcodecs-1.0.so.0.2402.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstinsertbin-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstinsertbin-1.0.so.0.2402.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstisoff-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstisoff-1.0.so.0.2402.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstmpegts-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstmpegts-1.0.so.0.2402.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstplay-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstplay-1.0.so.0.2402.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstplayer-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstplayer-1.0.so.0.2402.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstsctp-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstsctp-1.0.so.0.2402.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgsttranscoder-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgsturidownloader-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgsturidownloader-1.0.so.0.2402.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstva-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstva-1.0.so.0.2402.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstwayland-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstwayland-1.0.so.0.2402.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstwebrtc-1.0.so.0
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libgstwebrtc-1.0.so.0.2402.0
