name: fractal
adopt-info: fractal
grade: stable 
confinement: strict
base: core24
platforms:
  amd64:
  arm64:
    
slots:
  # for GtkApplication registration
  fractal:
    interface: dbus
    bus: session
    name: org.gnome.Fractal

apps:
  fractal:
    extensions: [gnome]
    command: usr/bin/fractal
    common-id: org.gnome.Fractal
    desktop: usr/share/applications/org.gnome.Fractal.desktop
    plugs:
      - network
      - network-status
      - audio-playback


parts:
  libshumate:
    source: https://gitlab.gnome.org/GNOME/libshumate.git
    source-tag: '1.3.0'
    plugin: meson
    meson-parameters: [ --prefix=/usr, -Dgir=false, -Dvapi=false, -Dgtk_doc=false, -Dsysprof=disabled]
    prime:
      - -usr/include
      - -usr/lib/*/pkgconfig
      - -usr/share

  grass:
    plugin: rust
    source: https://github.com/connorskees/grass.git
    source-type: git
    source-tag: '0.13.4'
    organize:
      grass: usr/bin/

  fractal:
    after: [ libshumate, pipewire, grass ]
    parse-info: [ usr/share/metainfo/org.gnome.Fractal.metainfo.xml ]
    source: https://gitlab.gnome.org/GNOME/fractal.git
    source-type: git
    source-tag: '10.1'
    plugin: meson
    meson-parameters: [--prefix=/snap/fractal/current/usr, -Dprofile=default, -Doptimization=3, -Dbuildtype=release]
    build-packages:
      - gperf
      - libssl-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-good1.0-dev
      - libprotobuf-c-dev
      - libclang-dev
      - libspa-0.2-dev
      - xdg-desktop-portal-dev
    build-environment:
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
      - PKG_CONFIG_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:$PKG_CONFIG_PATH 
      - PATH: $CRAFT_STAGE/usr/bin:$PATH
    organize: 
      snap/fractal/current: .
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/fractal/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done

  pipewire:
    source: https://gitlab.freedesktop.org/pipewire/pipewire.git
    source-tag: '0.3.79'
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - --strip
      - -Dalsa=disabled
      - -Dpipewire-alsa=disabled
      - -Djack=disabled
      - -Dpipewire-jack=disabled
      - -Dsession-managers=[]
      - -Dexamples=disabled
      - -Dman=disabled
      - -Dtests=disabled
    prime:
      - -usr/lib/*/pkgconfig
      - -usr/include

  # This is not available in the noble archive
  gst-plugin-gtk4:
    source: https://crates.io/api/v1/crates/gst-plugin-gtk4/0.13.4/download
    source-type: tar
    plugin: rust
    build-packages:
      - cargo-c
    override-build: |
      cargo cinstall --prefix "${SNAPCRAFT_PART_INSTALL}/usr" \
        --release \
        --library-type=cdylib \
        --features=gtk_v4_14,x11egl,x11glx,waylandegl,dmabuf
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/gstreamer-1.0/libgstgtk4.so

  deps:
    plugin: nil
    stage-packages:
      - gstreamer1.0-plugins-bad
      - libprotobuf-c1
    stage:
      # Use source-built pipewire
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/spa-0.2
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpipewire*
      # Use newer source-built librsvg from gnome-sdk
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/librsvg-2.so.*
    prime:
      - usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/spa-0.2
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/libpipewire*
      - -usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/librsvg-2.so.*
