name: fractal
adopt-info: fractal
grade: stable 
confinement: strict
base: core26
platforms:
  amd64:
  arm64:
    
slots:
  # for GtkApplication registration
  fractal:
    interface: dbus
    bus: session
    name: org.gnome.Fractal

apps:
  fractal:
    extensions: [gnome]
    command: usr/bin/fractal
    common-id: org.gnome.Fractal
    desktop: usr/share/applications/org.gnome.Fractal.desktop
    environment:
      # avoid crash when loading video if using vulkan
      GSK_RENDERER: ngl
    plugs:
      - network
      - network-status
      - audio-playback


parts:
  libshumate:
    source: https://gitlab.gnome.org/GNOME/libshumate.git
    source-tag: '1.6.1'
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --libdir=/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR
      - -Dgir=true
      - -Dvapi=false
      - -Dgtk_doc=false
      - -Dsysprof=disabled
    prime:
      - -usr/include
      - -usr/lib/*/pkgconfig
      - -usr/share

  grass:
    plugin: rust
    rust-channel: none # disable rustup, use build-packages
    source: https://github.com/connorskees/grass.git
    source-type: git
    source-tag: '0.13.4'
    organize:
      grass: usr/bin/
    build-packages:
      - rustc
      - cargo

  fractal:
    after: [ libshumate, grass ]
    parse-info: [ usr/share/metainfo/org.gnome.Fractal.metainfo.xml ]
    source: https://gitlab.gnome.org/World/fractal.git
    source-type: git
    source-tag: '14.1'
    plugin: meson
    meson-parameters: [--prefix=/snap/fractal/current/usr, -Dprofile=default, -Doptimization=3, -Dbuildtype=release]
    build-packages:
      - gperf
      - libssl-dev
      - libgstreamer1.0-dev
      - libgstreamer-plugins-bad1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libgstreamer-plugins-extra1.0-dev
      - libprotobuf-c-dev
      - libclang-dev
      - libspa-0.2-dev
      - xdg-desktop-portal-dev
      - rustc
      - cargo
    build-environment:
      - CARGO_BUILD_JOBS: $CRAFT_PARALLEL_BUILD_COUNT
      - PKG_CONFIG_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig:$PKG_CONFIG_PATH 
      - GI_TYPELIB_PATH: $CRAFT_STAGE/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/girepository-1.0:$GI_TYPELIB_PATH
      - PATH: $CRAFT_STAGE/usr/bin:$PATH
    organize: 
      snap/fractal/current: .
    override-build: |
      craftctl default
      mkdir -p $CRAFT_PART_INSTALL/meta/gui
      cp -r $CRAFT_PART_INSTALL/snap/fractal/current/usr/share/icons $CRAFT_PART_INSTALL/meta/gui/
      for i in `find $CRAFT_PART_INSTALL/meta/gui/icons -name "*.svg" -o -name "*.png"`; do
        mv $i "`dirname $i`/snap.$CRAFT_PROJECT_NAME.`basename $i`"
      done

  deps:
    plugin: nil
    stage-packages:
      - gstreamer1.0-plugins-bad
      - libprotobuf-c1
    stage:
      - usr/lib/
      - usr/share/
